swagger: "2.0"
info:
  version: 1.0.0
  title: "EsPreEs"
  description: Descrizione dell'api
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: nomeapp.herokuapp.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /astronauts:
    get:
      description: |
        Get all astronuts.
      operationId: getastronauts
      parameters:
        - name: lastName
          in: query
          description: lastname of astronauts to fetch
          required: false
          type: string
      responses:
        200:
          description: ritorna tutti gli elementi astronauts
          schema:
            type: array
            items:
              $ref: '#/definitions/astronauts'
        404:
          description: not found
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Crea un nuovo astronauta.  Duplicates are allowed
      operationId: addastronaut
      parameters:
        - name: astronauts
          in: body
          description: astronaut da aggiungere all'array
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        200:
          description: astronauts response
          schema:
            $ref: '#/definitions/astronauts'
        404:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /astronauts/{id}:
    get:
      description: ritorna astronauts con quel ID
      operationId: getastronautsID
      parameters:
        - name: id
          in: path
          description: ID of astronauts to fetch
          required: true
          type: string
      responses:
        200:
          description: astronauts response
          schema:
            $ref: '#/definitions/astronauts'
        404:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: put a single astronauts based on the ID supplied
      operationId: putastronauts
      parameters:
        - name: id
          in: path
          description: ID of astronauts to modify
          required: true
          type: string
      responses:
        200:
          description: astronauts modified
        404:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  astronauts:
    allOf:
      - $ref: '#/definitions/NewAstronaut'
      - properties:
          id:
            type: string
  NewAstronaut:
    required:
      - fistName
      - lastName
      - isInSpace
    properties:
      attributo1:
        type: string
      attributo2:
        type: string
      attributo3:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string